FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Chép file machine.py từ folder simulator
COPY simulator/machine.py .
CMD ["python", "machine.py"]