FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Chép file main.py từ folder app vào thư mục hiện tại trong container
COPY app/main.py .
CMD ["python", "main.py"]